version: "3"
services:
  notebook:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
    volumes:
      - ./:/home/rl_practice/
      # - $HOME/.git
    tty: true
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 300M
